# Garante que o Yarn crie a pasta node_modules física
nodeLinker: node-modules

# Aponta para o executável que deve estar no seu repositório
yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Silencia o erro que a Hostinger reportou
preferInteractive: false

# Evita problemas de rede em ambientes restritos
compressionLevel: mixed